version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pruebas
    ports:
      - "3305:3306"
    volumes:
      - ./data:/var/lib/mysql
