version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pruebas
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data